apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filer-sidecar-injector
  labels:
    app: filer-sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filer-sidecar-injector
subjects:
- kind: ServiceAccount
  name: filer-sidecar-injector
  namespace: das
